# Generated by Django 3.2.3 on 2021-06-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='email',
            new_name='reg_no',
        ),
    ]
