# Generated by Django 3.2.3 on 2021-06-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_email_courses_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now=True, null=True)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.users')),
            ],
        ),
    ]
