# Generated by Django 3.2.3 on 2021-06-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='reg_no',
            field=models.CharField(max_length=30),
        ),
    ]
