# Generated by Django 3.2.3 on 2021-06-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('course', 'number')},
        ),
    ]
