# Generated by Django 3.2.3 on 2021-06-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210625_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='branch',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('branch', 'number')},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
    ]
